/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function allocate_aligned_arena(byteLength: number): Buffer

export declare function leopard_encode(originalCount: number, shardSize: number, shardBytes: Buffer): Promise<number>

export declare function leopard_repair(originalCount: number, shardSize: number, missingIndices: Array<number>, shardBytes: Buffer): Promise<number>
